apiVersion: v1
kind: Service
metadata:
  name: go-echo
  namespace: go-echo
  labels:
    app: go-echo
spec:
  type: ClusterIP
  selector:
    app: go-echo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
